### ISSUE TITLE
Add IDE name display option

### ISSUE THREAD

**Issue by Rottenfront** [wavy-cat/wave-discord#1]
I didn't find any options to change the displayed IDE name, so I think it would be better to add some options to change it, like the 'JetBrains IDE' and '{IDE name}' options.

I would try to implement this feature if you don't want to.

**Comment by wavy-cat** [comment]
Hi, Rottenfront!

Unfortunately, this functionality cannot be implemented due to the specific characteristics of Discord activities (for more information, refer to the [Activity Struct](https://discord.com/developers/docs/game-sdk/activities#data-models-activity-struct)).

The only possible solution would be to create a new application on the Discord developer portal, but at the moment this cannot be done because of the direct storage of application icons in Discord.
